### ISSUE TITLE
Add more styles

### ISSUE THREAD

**Issue by tdwright** [tdwright/contabs#11]
Since 42b3ffcd it has been possible to build in styles. There aren't currently very many of these.

Let's add some more styles to ConTabs.

**Comment by iklen5** [comment]
Hello, I have previously used something similar to contabs (btw. good job on contabs).

Anyway, I was wondering if anyone is working on this? If not, I'd like to add few styles & tests. 

Have a good day!

**Comment by tdwright** [comment]
Hi @iklen5 

Thanks for your interest. I'm really glad you like ConTabs!

As far as I know, no-one else has taken this on. I'll assign it to you. The [contribution guidelines](https://github.com/tdwright/contabs/blob/master/CONTRIBUTING.md) should have all the info you need to get started.

I look forward to seeing a PR!

Tom

**Comment by iklen5** [comment]
Sorry, messed something up with previous PR.

**Comment by ErsinDagli** [comment]
Hi Tom its my first time creating a PR i apologise i didnt see that we needed to start a convo first

**Comment by tdwright** [comment]
@ErsinDagli No worries! I'll reply to the PR #58

**Comment by tdwright** [comment]
NB: I'm closing this issue now.

I think it's best in future for styles to be posted to their own issues like we've done with #61 and #64.

PS @ErsinDagli Your PR is still open. Please let me know if you're still working on it or if you'd like me to finish it. Either way is fine! 😄  - Tom

**Comment by edzcodes** [comment]
G’day Tom,

Sorry for the late reply, thanks for the tips just been caught up with work, will do my best to finish it over the weekend.

cheers


________________________________

**Comment by tdwright** [comment]
G'day from Melbourne mate!

No worries at all. I know what it's like trying to fit life around work. Just glad you haven't gone and disappeared!
