### ISSUE TITLE
Shouldn't be possible to make a table if there aren't any valid columns

### ISSUE THREAD

**Issue by tdwright** [tdwright/contabs#13]
Currently if you try to make a table from a class without any public properties, you get a wonky table without any headers or content, although the correct numbers of (empty) rows do get printed.

When creating a table, we should check to see how many valid columns are present. The either throw an exception, or handle the "no column" case like we do the "no data" case.

Related: what happens if there are valid columns, but they're all set to "hide"?

**Comment by rahl0b10** [comment]
I'm guessing this can be closed, @tdwright ?

**Comment by tdwright** [comment]
Absolutely. Thanks again for your contribution @rahl0b10!

I think the related problem of what to do when all columns are set to "hidden" may still need addressing, but this should be done with a separate issue.

Tom
