### ISSUE TITLE
Allow for alignment of data in columns to be controlled

### ISSUE THREAD

**Issue by tdwright** [tdwright/contabs#15]
An obvious example would be for numbers with decimal places:

```
+--------+--------+
| Apple  | Orange |
+--------+--------+
|  12.50 | ABC    |
| 123.21 | AB     |
+--------+--------+
```

**Comment by Royhoey** [comment]
Hey! Can I try this one? :)

My approach would be to create a new class Allignment with a ProcessString function, similar to LongStringBehaviour. This could thenn be a property on the Column class so you can configure the allignment for each column.

**Comment by Royhoey** [comment]
Which options are there for alignment? Just left and right or center as well? What would a center alignment look like if the column max width is an odd number?

**Comment by tdwright** [comment]
Hi @Royhoey!

You are (of course) very welcome to take this one on. Thanks for sticking your hand up!

I think having centre alignment would be worthwhile, but I don't think the most important thing is for it to be 100% perfectly centred. For odd numbered widths, it might just be an arbitrary decision as to which way round the asymmetry goes.

The other way to handle this, I guess, would be to force all centre-aligned columns to have an even numbered width. Let's do it the straightforward way first and see how it looks. If it looks janky to have a slight asymmetry, we can always go down this route in the future.

In terms of how to implement this, your approach sounds like it could work, but at present the implicit/default left-align takes place in the [`DataLine()` method of `OutputBuilder.cs`](https://github.com/tdwright/contabs/blob/master/ConTabs/OutputBuilder.cs#L97). You could consider making a "left pad" and "right pad" property on the column class perhaps? Then where would you do the calculation that takes the alignment into account? Hmmm....

**Comment by Royhoey** [comment]
@tdwright Alright I will give it a go then! 

As far as the centre alignment goes, I'll just play around with it to see how it looks.
Yeah I was thinking that the aligning should take place in the DataLine method... let me see what works best.

**Comment by tdwright** [comment]
Awesome. Look forward to seeing a PR soon! :grinning:
