### ISSUE TITLE
Handle nulls in a more dignified manner

### ISSUE THREAD

**Issue by tdwright** [tdwright/contabs#40]
It seems to me that the expected behaviour for null values should be an empty string, not a `NullReferenceException` as is currently the case.

```C#
var Data = DemoDataProvider.ListOfDemoData();
Data[0].StringCol = null;
var table = Table<DemoDataType>.Create(Data);
Console.WriteLine(table.ToString());
```

This should be rendered like:

```
+-----------+--------+
| StringCol | IntCol |
+-----------+--------+
|           | 2      |
| Dogs      | 1      |
| Chickens  | 3      |
+-----------+--------+
```

This will help if/when we start to tackle anonymous objects (e.g. #35).

**Comment by MichaelStedman** [comment]
I read your recent blog about "Attracting contributors to ConTabs".

Would you like me to look at this issue?

**Comment by tdwright** [comment]
Hi @MichaelStedman - great to have you here. If you'd like to tackle this one, it would be appreciated.

**Comment by tdwright** [comment]
Thanks @MichaelStedman! This will be included in the next release, which should be this weekend.
