### ISSUE TITLE
Add intellisense / XML documentation

### ISSUE THREAD

**Issue by tdwright-itg** [tdwright/contabs#46]
It would be useful to add XML comments to the code to power intellisense. This would aid discovery and allow people to do more with ConTabs without needing to read the online documentation.

As per http://blog.tdwright.co.uk/2017/07/25/using-xml-comments-to-provide-intellisense-hints/

**Comment by Chandler-Davidson** [comment]
I'm interested in taking this one! I'll add a PR asap.

**Comment by tdwright** [comment]
Fixed in #51
