### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by levimatheri** [tdwright/contabs#52]
Why am I getting these errors?

`Install-Package : NU1108: Cycle detected. 
  ConTabs.tdwright -> ConTabs.tdwright (>= 1.2.0).
At line:1 char:1
 Install-Package ConTabs.tdwright -Version 1.2.0
     CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
     FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'ConTabs'.
At line:1 char:1
Install-Package ConTabs.tdwright -Version 1.2.0
     CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
     FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand`

**Comment by Chandler-Davidson** [comment]
Seems like an issue with Nuget or VS, here's some [help](https://stackoverflow.com/questions/8314400/nuget-add-reference-error-while-installing-packages).

**Comment by levimatheri** [comment]
Thank you but that didn't help. I fixed it by going to ConTabsDemo-DotNetCore, there was an error there and I simply removed the dependency then installed the package again and voila!
