### ISSUE TITLE
Enhancement: New style - Empty

### ISSUE THREAD

**Issue by pykong** [tdwright/contabs#61]
AFAIK - there is no style which uses just ` `  (space) as the delimiter.
I feel such style, which is the most minimal style possible, is painfully missing from the defaults.
It is great to enhance readability of the data printed.

**Comment by tdwright** [comment]
Good call @pykong - this could look great for some datasets.

A nice first issue for someone too, if anyone's keen?

**Comment by tdwright** [comment]
Merged #66 so closing this issue. Functionality will be released as part of [v2.0](https://github.com/tdwright/contabs/milestone/1). Thanks @pykong and @wargamer!
