### ISSUE TITLE
New unicode styles

### ISSUE THREAD

**Issue by tdwright** [tdwright/contabs#64]
Doubled walled
```
╓──╥──╖
║  ║  ║ 
╟──╫──╢
║  ║  ║ 
╙──╨──╜ 
```

Double floored
```
╒══╤══╕
│  │  │
╞══╪══╡
│  │  │
╘══╧══╛ 
```

**Comment by oisinmcl** [comment]
Hi, 
Is this issue being worked on? I would like to start contributing and I feel this would be a good first contribution. 

Thanks
Oisin

**Comment by tdwright** [comment]
Hi @oisinmcl! 👋 

It's all yours if you want it. And you're just in time for the [version 2.0](https://github.com/tdwright/contabs/milestone/1) milestone.

Have a look at the [contributor guidelines](https://github.com/tdwright/contabs/blob/master/CONTRIBUTING.md) and in particular the section on testing. For new styles, we tend to need one test per style.

Let me know if I can help at all. Otherwise I shall eagerly anticipate a pull request!

Tom 😄

**Comment by oisinmcl** [comment]
Hi Tom, 

OK I will start this today. I had a read over the guidelines and will contact if I need help. 

Looking forward to contributing. 

Thanks
Oisin
