### ISSUE TITLE
Review and update all dependencies

### ISSUE THREAD

**Issue by tdwright** [tdwright/contabs#65]
- [ ] Do we still need all our dependencies?

- [ ] Are they all up to date?

**Comment by pykong** [comment]
Is there any dependency checker similar maybe to `vulture` in python?

The only ones I came across are
- CodeRush (no good for this purpose)
- ReSharper/Rider (Haven't tried)

**Comment by tdwright** [comment]
Good call re: ReSharper. Used to use it in my last job and it was very good. Not specifically for dependency checking _per se_, but still a very good tool. I should see if they'd do me an open source version for ConTabs...

I've been working on this one in a fairly manual way, assisted by the NuGet package manager. It's made simpler by the fact that ConTabs itself has no dependencies outside of .NET standard. All the dependencies I'm talking about are on the testing and tooling side of things.

Think I've nailed it for now, anyway. 😄

**Comment by pykong** [comment]
@tdwright Great to see the pace this project is moving forward.
