### ISSUE TITLE
Add derived computed columns

### ISSUE THREAD

**Issue by tdwright** [tdwright/contabs#7]
Possibly by using delegates?

E.g. turning a date and end date into days relative to today, or multiplying a rate by a quantity to get a subtotal.

**Comment by levimatheri** [comment]
Hi @tdwright, I am a newbie here but I'd like to take on this. I'm more experienced in Java but I'd like to enhance my C#

**Comment by tdwright** [comment]
Hi @levimatheri.

Please, be my guest! I think this could be a great feature.

Have you had any thoughts about how you'd plan on approaching it?

Tom

**Comment by levimatheri** [comment]
Thank you.

Not yet but I will.

Levi

**Comment by Chandler-Davidson** [comment]
I'm really interested in this improvement, however I think it is more complex than it seems. Either you have to have a table of two different types or create a new table of the a new derived type that expands upon the generic. 

I looked at using the ExpandoObject to add properties to an object, but ran into some troubles.

**Comment by Chandler-Davidson** [comment]
I've made some [progress](https://github.com/Chandler-Davidson/contabs/blob/ComputeColumn/ConTabs/Columns.cs), but am still running into troubles. My first thought was to add a column to the existing table, but ran into issues where the method needs to know the table's type. Otherwise I get a casting exception. Any help, @tdwright?

**Comment by tdwright** [comment]
Hi @Chandler-Davidson. What you've done looks like a good start. I'll have a proper look ASAP.

**Comment by levimatheri** [comment]
@Chandler-Davidson , does this work? NB: I am very new to C#

`var first_type = this[first].Values[first].GetType();
            var second_type = this[second].Values[second].GetType();

            if (first_type != second_type)
                throw new Exception("Columns to derive from must be of the same type");

            if(typeof(T) != first_type)
                throw new Exception("Custom method does not take in correct types");

            var data = new List<T>();

            for (int i = 0; i < this[first].Values.Count; i++)
            {
                data.Add(method((T)this[first].Values[i], (T)this[second].Values[i]));
                
            }

            var newData = data
                .Cast<List<object>>()
                .Select(x => new Column(first_type, name)
                {
                    SourceType = x.GetType()
                }).ToList();

            AddRange(newData);
`

**Comment by levimatheri** [comment]
I just realized columns to derive from could be of different types as in the case of multiplying an int value with a double (rates could be floating points)

**Comment by levimatheri** [comment]
Hi @Chandler-Davidson your approach worked for me!

**Comment by Chandler-Davidson** [comment]
We can close this issue after pull request #53.

**Comment by Chandler-Davidson** [comment]
Just looked through the changes and am really excited about the changes!

I'll create an issue to update the docs to cover these changes and have a pull request by tonight.

**Comment by tdwright** [comment]
Awesome. Glad to hear it.

Don't worry about a PR for the doc changes, just do them directly in the wiki. (Unless you also wanted to update the Intellisense/XML docs?)

**Comment by tdwright** [comment]
Now released. Closing the issue.
