### ISSUE TITLE
Chinese is not supported

### ISSUE THREAD

**Issue by fangjunai** [tdwright/contabs#72]
table.TableStyle = Style.UnicodeLines;

Chinese is not supported.

**Comment by tdwright** [comment]
Hi @fangjunai.

What do you mean? Could you give me a case to reproduce? ([Tips here](https://stackoverflow.com/help/minimal-reproducible-example))

The line you've included is really only used to change the style (theme) of the table. There is a page in the wiki which [explains and lists the styles you can choose from](https://github.com/tdwright/contabs/wiki/2.-Styling-your-table).

**Comment by tdwright** [comment]
It's been over a year without being able to repro. Closing this issue for now, but happy to reopen if needed.
